"""initial control-plane schema

Creates every table from the ORM metadata so the migration can never drift from the
models. Subsequent schema changes get their own autogenerated revisions.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-06
"""

from __future__ import annotations

from alembic import op
from upm_control_plane import models  # noqa: F401  (populate metadata)
from upm_control_plane.base import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
